# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configurations are located in `C:\Users\Nicholas\AppData\Roaming\YGOFabrica\config.toml`.

[expansion.Testing]
default = true
recipe = ["Testing-vals.toml","Testing-en.toml"]
locale = 'en'

[gamedir.main]
path = '''C:\ProjectIgnis'''

[picset.regular]
default = true
mode = 'proxy'
size = '512x'
artstyle = 'cover'
ext = 'png'
field = true
author = 'Nbashpro'
year = 2023

