[macro]
_SETN = "FABK-$1$2"

[counter.production]
code = 0x12f

[set.guardian]
code = 0x52

[set.Testing]
name = "Testing"
code = 0xf00

[card.test]
id = 102345678
setnumber = "${SETN|001}"
ot = "custom"
set = "Testing"
attribute = "water"
race = "spellcaster"
type = "monster effect normal"
atk = 5000
def = 420
level = 12
